---
- name: activity 3
  hosts: all
  become: yes
  tasks:
  - name: install httpd and php packages
    ansible.builtin.dnf:
      name:
      - httpd
      - php 
      - php-cli 
      - php-common  
      state: present

  - name: copy php file
    ansible.builtin.copy:
      content: <?php phpinfo(); ?>
      dest:  /var/www/html/info.php


