---
- name: activity 4
  hosts: all
  become: true
  tasks:
  - name: print the value for purpose
    ansible.builtin.debug:
      var: purpose
  - name: fail on unsupported operating systems
    ansible.builtin.fail:
      msg: "This playbook will work on Debian and RedHat Only"
    when: ansible_facts["os_family"] != "Debian" and ansible_facts["os_family"] != "RedHat"   
  - name: install httpd/apache2 and php packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present  
    loop: "{{ all_packages }}"       
  - name: copy php file
    ansible.builtin.copy:
      content: <?php phpinfo(); ?>
      dest:  /var/www/html/info.php
  - name: ensure httpd service should be started and enabled
    ansible.builtin.service:
      name: "{{ package_name }}"
      state: started
      enabled: true
