---
- name: activity 4
  hosts: all
  become: true
  tasks:
  - name: fail on unsupported operating systems
    ansible.builtin.fail:
      msg: "This playbook will work on Debian and RedHat Only"
    when: ansible_facts["os_family"] != "Debian" and ansible_facts["os_family"] != "RedHat"
  - name: print the value
    ansible.builtin.debug:
      var: all_packages   
  - name: installing apache2 and php packages
    ansible.builtin.apt:
      name: "{all_packages}"
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"  
  - name: install httpd and php packages
    ansible.builtin.yum:
      name: "{all_packages}"
      state: present  
    when: ansible_facts['os_family'] == "RedHat"     
  - name: copy php file
    ansible.builtin.copy:
      content: <?php phpinfo(); ?>
      dest:  /var/www/html/info.php
  
  - name: ensure httpd service should be started and enabled
    ansible.builtin.service:
      name: "{package_name}"
      state: started
      enabled: true
    when: ansible_facts['os_family'] == "RedHat"