---
- name: activity 4
  hosts: all
  become: true
  tasks:
  - name: fail on unsupported operating systems
    ansible.builtin.fail:
      msg: "This playbook will work on Debian and RedHat Only"
    when: ansible_facts["os_family"] != "Debian" and ansible_facts["os_family"] != "RedHat"
  - name: installing apache2 and php packages
    ansible.builtin.apt:
      name: 
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"  
  - name: install httpd and php packages
    ansible.builtin.yum:
      name:
      - httpd
      - php 
      - php-cli 
      - php-common 
      - php-gd 
      - php-mysqlnd 
      - php-pdo 
      state: present  
    when: ansible_facts['os_family'] == "RedHat"     
  - name: copy php file
    ansible.builtin.copy:
      content: <?php phpinfo(); ?>
      dest:  /var/www/html/info.php
  
  - name: ensure httpd service should be started and enabled
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
    when: ansible_facts['os_family'] == "RedHat"